[dependencies]
"wasmer/php" = "^8.3"

[[command]]
name = "script"
module = "wasmer/php:php"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["-t", "/app", "-S", "0.0.0.0:8080"]

[fs]
"/app" = "app"
